var BOOKS = [
  {title:"魔女之旅 第01卷", file:"魔女之旅 第01卷.epub", cover:"books/covers/魔女之旅 第01卷.jpg", cat:"main"},
  {title:"魔女之旅 第02卷", file:"魔女之旅 第02卷.epub", cover:"books/covers/魔女之旅 第02卷.jpg", cat:"main"},
  {title:"魔女之旅 第03卷", file:"魔女之旅 第03卷.epub", cover:"books/covers/魔女之旅 第03卷.jpg", cat:"main"},
  {title:"魔女之旅 第04卷", file:"魔女之旅 第04卷.epub", cover:"books/covers/魔女之旅 第04卷.jpg", cat:"main"},
  {title:"魔女之旅 第05卷", file:"魔女之旅 第05卷.epub", cover:"books/covers/魔女之旅 第05卷.jpg", cat:"main"},
  {title:"魔女之旅 第06卷", file:"魔女之旅 第06卷.epub", cover:"books/covers/魔女之旅 第06卷.jpg", cat:"main"},
  {title:"魔女之旅 第07卷", file:"魔女之旅 第07卷.epub", cover:"books/covers/魔女之旅 第07卷.jpeg", cat:"main"},
  {title:"魔女之旅 第08卷", file:"魔女之旅 第08卷.epub", cover:"books/covers/魔女之旅 第08卷.jpeg", cat:"main"},
  {title:"魔女之旅 第09卷", file:"魔女之旅 第09卷.epub", cover:"books/covers/魔女之旅 第09卷.jpeg", cat:"main"},
  {title:"魔女之旅 第10卷", file:"魔女之旅 第10卷.epub", cover:"books/covers/魔女之旅 第10卷.jpeg", cat:"main"},
  {title:"魔女之旅 第11卷", file:"魔女之旅 第11卷.epub", cover:"books/covers/魔女之旅 第11卷.jpg", cat:"main"},
  {title:"魔女之旅 第12卷", file:"魔女之旅 第12卷.epub", cover:"books/covers/魔女之旅 第12卷.jpg", cat:"main"},
  {title:"魔女之旅 第13卷", file:"魔女之旅 第13卷.epub", cover:"books/covers/魔女之旅 第13卷.jpg", cat:"main"},
  {title:"魔女之旅 第14卷", file:"魔女之旅 第14卷.epub", cover:"books/covers/魔女之旅 第14卷.jpg", cat:"main"},
  {title:"魔女之旅 第15卷", file:"魔女之旅 第15卷.epub", cover:"books/covers/魔女之旅 第15卷.jpeg", cat:"main"},
  {title:"魔女之旅 第16卷", file:"魔女之旅 第16卷.epub", cover:"books/covers/魔女之旅 第16卷.jpg", cat:"main"},
  {title:"魔女之旅 第17卷", file:"魔女之旅 第17卷.epub", cover:"books/covers/魔女之旅 第17卷.jpg", cat:"main"},
  {title:"魔女之旅 18", file:"白石定规 - 魔女之旅 18.epub", cover:"books/covers/白石定规 - 魔女之旅 18.jpg", cat:"main"},
  {title:"魔女之旅 19", file:"白石定规 - 魔女之旅 19.epub", cover:"books/covers/白石定规 - 魔女之旅 19.jpg", cat:"main"},
  {title:"魔女之旅 20", file:"魔女之旅 20.epub", cover:"books/covers/魔女之旅 20.jpg", cat:"main"},
  {title:"魔女之旅 21", file:"魔女之旅 21.epub", cover:"books/covers/魔女之旅 21.jpg", cat:"main"},
  {title:"祈祷之国的莉莉艾儿 01", file:"白石定规 - 魔女之旅 外传 祈祷之国的莉莉艾儿 01.epub", cover:"books/covers/白石定规 - 魔女之旅 外传 祈祷之国的莉莉艾儿 01.jpg", cat:"spin"},
  {title:"祈祷之国的莉莉艾儿 02", file:"白石定规 - 魔女之旅 外传 祈祷之国的莉莉艾儿 02.epub", cover:"books/covers/白石定规 - 魔女之旅 外传 祈祷之国的莉莉艾儿 02.jpg", cat:"spin"},
  {title:"莉莉艾尔与祈祷之国", file:"白石定规 - 魔女之旅 番外 莉莉艾尔与祈祷之国.epub", cover:"books/covers/白石定规 - 魔女之旅 番外 莉莉艾尔与祈祷之国.jpg", cat:"extra"},
  {title:"魔女之旅 学园", file:"白石定規 - 魔女之旅 學園.epub", cover:"books/covers/白石定規 - 魔女之旅 學園.jpg", cat:"extra"}
];